# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

stages:
  - test
  - lint
  - build

unit_and_integration_tests:
  tags:
    - Linux
  image: ghcr.io/astral-sh/uv:debian
  before_script:
    - apt update
    - apt install -y cmake libdbus-1-dev python3-dev
    - cmake --version
    - uv --version
    - uv venv .venv
    - uv pip install -r pyproject.toml --group dev
    - uv pip tree
    - export PYTHONPATH="$PYTHONPATH:$(pwd)"
  script:
    - uv run --no-project pytest --cov --cov-report term --cov-report xml:coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  coverage: '/TOTAL.*\s+(\d+%)$/'

# ---

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/website-sphinx-app-docs.yml
      - /gitlab-templates/reuse-lint.yml

variables:
    WEBSITE_LANGUAGES: en
    DOC_ROOT: doc

reuse:
  stage: lint

ruff:
  stage: lint
  image: registry.gitlab.com/pipeline-components/ruff:latest
  script:
    - ruff check --output-format=gitlab .
