# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

stages:
  - test
  - lint
  - build

unit_and_integration_tests:
  tags:
    - Linux
  image: python:3.9  # keep same version as defined in Pipfile
  before_script:
    - apt update
    - apt install -y cmake libdbus-1-dev
    - cmake --version
    - python --version
    - pip install pipenv --quiet
    - pipenv install --dev
    - pipenv graph
    - export PYTHONPATH="$PYTHONPATH:$(pwd)"
  script:
    - pipenv run pytest --cov --cov-report term --cov-report xml:coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  coverage: '/TOTAL.*\s+(\d+%)$/'

# ---

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/website-sphinx-app-docs.yml
      - /gitlab-templates/reuse-lint.yml

variables:
    WEBSITE_LANGUAGES: en
    DOC_ROOT: doc

build_sphinx_app_docs:
  before_script:
    - python3 -m pip install sphinx myst-parser sphinx-book-theme
    - git clone https://invent.kde.org/sysadmin/ci-utilities.git
    - git clone https://invent.kde.org/sysadmin/ci-notary-service.git

reuse:
  stage: lint

ruff:
  stage: lint
  image: registry.gitlab.com/pipeline-components/ruff:latest
  script:
    - ruff check --output-format=gitlab .
